name: LAB EKS Deploy Step-by-Step

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v2
      - run: terraform -chdir=eks-lab-terraform/infra init
      - run: terraform -chdir=eks-lab-terraform/infra apply -auto-approve
    
  deploy_nginx:
    needs: terraform
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - run: aws eks update-kubeconfig --region us-east-1 --name eks-lab
      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - run: |
          kubectl apply -f eks-lab-terraform/k8s/00-namespace.yaml
          kubectl apply -f eks-lab-terraform/k8s/01-deployment.yaml
          kubectl apply -f eks-lab-terraform/k8s/02-service-nginx.yaml
      - run: |
          kubectl scale deployment nginx --replicas=8 -n nginx
          kubectl scale deployment nginx --replicas=2 -n nginx
          kubectl apply -f eks-lab-terraform/k8s/03-deployment-v1.yaml
          kubectl apply -f eks-lab-terraform/k8s/04-deployment-v2.yaml
          kubectl rollout history deployment nginx -n nginx
          kubectl rollout undo deployment/nginx --to-revision=1 -n nginx
          kubectl delete -f eks-lab-terraform/k8s/02-service-nginx.yaml
          kubectl delete -f eks-lab-terraform/k8s/01-deployment.yaml
nx.yaml
          kubectl delete -f k8s/01-deployment.yaml
